#!/usr/bin/env python
# Generated by Cursor using models Codex 5.3, Sonnet 4.6 & 5, Composer 2.5
"""
Launch libvirt-based integration tests.

Similar to runqemu.py but uses the libvirt Python API to create virtual
machines instead of the standard-inventory-qcow2 script.  Supports creating
multiple VMs on a shared virtual network so they can reach each other.
"""

import hashlib
import logging
import os
import re
import shlex
import shutil
import subprocess  # nosec
import sys
import tempfile
import time
import uuid

import defusedxml.ElementTree as ET
import yaml

# Import shared helpers from runqemu in the same directory.
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
if _SCRIPT_DIR not in sys.path:
    sys.path.insert(0, _SCRIPT_DIR)

import runqemu as rq  # noqa: E402

try:
    import libvirt
except ImportError:
    libvirt = None

try:
    ProcessLookupError
except NameError:
    ProcessLookupError = OSError

# Keep in sync with standard-inventory-qcow2
IDENTITY = """-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEAxegy2vpfopFtj2yfL/vqKDYzmK8wg5tTEZ83LNvN1urv9wWKtn3o
0N8b7cofK4TG6lnS/PV5VrPMo3VYCAAKCtc26hDjPDfCAecAUaO3UyL7bHPf3SDhF0kgV+
Vtk+oRgPxuktW7DqxBRZxoqlqNek/fbbK/HkdsrYKhcGjvVzt5p9nBFZIdDdLue5bOf5mh
hYqXVvRsyyy/QH0IHyWqJPdGS5vtldELN4LmRIxO+b0kR3+SNfpXkx31FG49FPfOA2KkN6
GlkGI6mgV+MELvSE0hzwzkNBzyitUC/u2q9Qqz8AWnraoewjDa9H0IgUKR87J+zKsuF4wk
lEi7tsurf0B8OPL4/I7WiG5FfYNHmSdyDdqMSsceSJtGyJ0dBzdqRCjSk7tG7bgEiShDRU
M00WAy1S3xjzQh24aMdOW3NMsY6wLJ4IdClvmoqgBJepXdEg4o3sNDkLHoLRFU2OFFBuZr
NUTIsSp68UQmQ3dFxLZGPlMhJPJxJ17dSSfezIB1AAAFqBM8kCUTPJAlAAAAB3NzaC1yc2
EAAAGBAMXoMtr6X6KRbY9sny/76ig2M5ivMIObUxGfNyzbzdbq7/cFirZ96NDfG+3KHyuE
xupZ0vz1eVazzKN1WAgACgrXNuoQ4zw3wgHnAFGjt1Mi+2xz390g4RdJIFflbZPqEYD8bp
LVuw6sQUWcaKpajXpP322yvx5HbK2CoXBo71c7eafZwRWSHQ3S7nuWzn+ZoYWKl1b0bMss
v0B9CB8lqiT3Rkub7ZXRCzeC5kSMTvm9JEd/kjX6V5Md9RRuPRT3zgNipDehpZBiOpoFfj
BC70hNIc8M5DQc8orVAv7tqvUKs/AFp62qHsIw2vR9CIFCkfOyfsyrLheMJJRIu7bLq39A
fDjy+PyO1ohuRX2DR5kncg3ajErHHkibRsidHQc3akQo0pO7Ru24BIkoQ0VDNNFgMtUt8Y
80IduGjHTltzTLGOsCyeCHQpb5qKoASXqV3RIOKN7DQ5Cx6C0RVNjhRQbmazVEyLEqevFE
JkN3RcS2Rj5TISTycSde3Ukn3syAdQAAAAMBAAEAAAGAJChDnlFPBq8GMsV4Ifam9bjNXX
BobysCFr6dgIMaDNF4jQuEp8nCLuMMQboDTtqf0vIdQ5z/kbEgyp5mOnPzYb6nKEV0lqxj
NCDFpKTCGhzSjaJv/IEEztHL6HMgvXzuvL+h3g7RcaFT/YlRcApCPd345pxZIYmQF/U9VI
G/dJMHq3xzs+KxjzSB4K+RQ6vIYFMNSlQ2yjn/KSOOx84EU2OgArFWy1/ZakdulYiC50rA
pZVvm5AEzvqSq6xmWX3aYfFmzwe8cNxMZHF9u58fKnqtUZfzlaxxHx1MX34nkqEEdvpmw0
ha06OkLp5oELr4J/Fw9vAhRaX7y+su0PauX4WqIGutE6ykzW9u0y1LdWon4vZupCWML3TT
fMSwkaihxQSvU47/YZT0tqSGuLk8hUQDygmGDK+OJktGBhD4NojzUIMnd8Pvq+8ObbaXPa
JWuBy3+/rG7WqGHos8vOL5GrJWebi5sPKo9x8dvXNyChUcX3Ott7ITtlCSFjXMQ5+hAAAA
wF8uLNq/BGomZWkveTsnurXzWCh/p1gGt/E6LPetEWp0YMzdKWLF4Mx1u6qCEcwP4ss7de
KTlwtkFMmjqU13bu85mduEPCaP9oIRs+ayUR17i5IddcotkE4xHe+zaUyUXgaT3fH3FAvn
RN0OlhR/hPtlT/l/b8oTO7TN6vNMWa9heBTN9hElc/OIEN9iBkxmf2XMgs7Lp74tGoptQq
38xu3M3o/l32zLz0B2ZGYT9btc1LvImK4fIhl6vbU/zdQ6yQAAAMEA4iiYASLGuyz5cQa1
0de+wJ12tPiKtnkZm4plD43enscC8ZTKGINcU+FeL/6pS7+Ivlhvt0u440Y9opNjQPGo+k
sbXdjQOO4NjVqRWPZbJhS2bqe++UHZf7vofjuA1amddpfUimx/0Ax41h2nO4c8VSs3tDrF
u23UvHz8Jfin/hnsgIjZLfLDbzm+nTnWd+v9u01IQqteyADOwiIjrO4qIzlqGjNMYux3eu
2Lb2Ip01we9jTROUOjgo1IDPB4rJhFAAAAwQDgBUvoMDkDkQ6kt14uDxurz98t2cjRDkCI
cSqUrWXB+ko6eDnbbT+zHSEahDG1UvQbkJTPir+7F+Rx2mdZSYjGMJPxX85x+1JObIuEc0
vQHm6rtb62viUAnIM2diZN8Wcf5KWk2uAIgcBIYSO2sW99QPwnY7H23ljiPlA79iwZQh2O
pyOd+KUAak86QwuetTJRXepa40R37YUcLqIBP4euPz5cF8txKOxocywTZaDlqhth0RT/n+
RwE9fnioxlwnEAAAAucm1lZ2dpbnNAcm1lZ2dpbnMtdGhpbmtwYWR0MTRzZ2VuMmkucmVt
b3RlLmNzYgECAwQF
-----END OPENSSH PRIVATE KEY-----
"""
AUTH_KEY = (
    "AAAAB3NzaC1yc2EAAAADAQABAAABgQDF6DLa+l+ikW2PbJ8v++ooNjOYrzCDm1MRnz"
    "cs283W6u/3BYq2fejQ3xvtyh8rhMbqWdL89XlWs8yjdVgIAAoK1zbqEOM8N8IB5wBR"
    "o7dTIvtsc9/dIOEXSSBX5W2T6hGA/G6S1bsOrEFFnGiqWo16T99tsr8eR2ytgqFwaO"
    "9XO3mn2cEVkh0N0u57ls5/maGFipdW9GzLLL9AfQgfJaok90ZLm+2V0Qs3guZEjE75"
    "vSRHf5I1+leTHfUUbj0U984DYqQ3oaWQYjqaBX4wQu9ITSHPDOQ0HPKK1QL+7ar1Cr"
    "PwBaetqh7CMNr0fQiBQpHzsn7Mqy4XjCSUSLu2y6t/QHw48vj8jtaIbkV9g0eZJ3IN"
    "2oxKxx5Im0bInR0HN2pEKNKTu0btuASJKENFQzTRYDLVLfGPNCHbhox05bc0yxjrAs"
    "ngh0KW+aiqAEl6ld0SDijew0OQsegtEVTY4UUG5ms1RMixKnrxRCZDd0XEtkY+UyEk"
    "8nEnXt1JJ97MgHU="
)
DEF_USER = "root"
# to be compatible with standard-inventory-qcow2
DEF_PASSWD = "foobar"  # nosec
DEFAULT_LIBVIRT_URI = "qemu:///system"
DEFAULT_MEMORY_MIB = 2048
DEFAULT_VCPUS = 2
SSH_WAIT_TIMEOUT = 600
MIN_LIBVIRT_NVME_VERSION = 11006000
HOSTS_MARKER_BEGIN = "# BEGIN lsr-libvirt-hosts"
HOSTS_MARKER_END = "# END lsr-libvirt-hosts"
FMF_ROOT = "standard-inventory-qcow2"
HOSTNAME_LABEL_RE = re.compile(
    r"^[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?$"
)
MAX_HOSTNAME_LENGTH = 253


def is_valid_hostname(hostname):
    """Return True if hostname is a valid DNS/RFC 1123 hostname."""
    if not hostname or len(hostname) > MAX_HOSTNAME_LENGTH:
        return False
    if hostname.endswith("."):
        hostname = hostname[:-1]
    labels = hostname.split(".")
    if not labels:
        return False
    return all(HOSTNAME_LABEL_RE.match(label) for label in labels)


def validate_hostnames(hostnames):
    """Ensure hostnames are unique and each is a valid hostname string."""
    if not hostnames:
        raise ValueError("At least one hostname is required.")
    seen = set()
    duplicates = []
    invalid = []
    for hostname in hostnames:
        if not is_valid_hostname(hostname):
            invalid.append(hostname)
        elif hostname in seen:
            duplicates.append(hostname)
        else:
            seen.add(hostname)
    errors = []
    if invalid:
        errors.append(
            "Invalid hostname(s): {}. Hostnames must be DNS names "
            "using letters, digits, and hyphens; each label must start "
            "and end with a letter or digit.".format(", ".join(invalid))
        )
    if duplicates:
        errors.append(
            "Duplicate hostname(s): {}. Each --hostnames value must be "
            "unique.".format(", ".join(sorted(set(duplicates))))
        )
    if errors:
        raise ValueError(" ".join(errors))
    return hostnames


def get_provision_fmf(tests_dir=None):
    """Return contents of provision.fmf in dict format."""
    search_dirs = []
    if tests_dir:
        search_dirs.append(tests_dir)
    search_dirs.extend([".", "tests"])
    seen = set()
    for directory in search_dirs:
        directory = os.path.abspath(directory)
        if directory in seen:
            continue
        seen.add(directory)
        provision_fmf = os.path.join(directory, "provision.fmf")
        if os.path.exists(provision_fmf):
            logging.info("Using provision.fmf from %s", provision_fmf)
            with open(provision_fmf) as fd:
                data = yaml.safe_load(fd)
                return data if isinstance(data, dict) else {}
    return {}


def fmf_get(path, default=None, tests_dir=None):
    """Return parameter from provision.fmf at desired path or default."""
    tree = get_provision_fmf(tests_dir)
    logging.debug("fmf_get path %s tests_dir %s", path, tests_dir)
    if not tree:
        return default
    subtree = tree.get(FMF_ROOT, {})
    for item in path:
        if not isinstance(subtree, dict):
            return default
        subtree = subtree.get(item)
        if subtree is None:
            return default
    if isinstance(subtree, dict) and default is not None and not subtree:
        return default
    return subtree


def sanitize_libvirt_name(name):
    """Return a name valid for libvirt domains and networks."""
    name = re.sub(r"[^A-Za-z0-9_.-]", "-", name)
    if not name[0].isalpha():
        name = "lsr-" + name
    return name[:64]


def find_isomaker():
    """Find a program that can create cloud-init ISO images."""
    for candidate in (
        "/usr/bin/genisoimage",
        "/usr/bin/mkisofs",
        "/usr/bin/xorriso",
    ):
        if os.path.isfile(candidate) and os.access(candidate, os.X_OK):
            return candidate
    return None


def find_ansible():
    """Find ansible executable."""
    for candidate in ("ansible", "ansible-3"):
        path = shutil.which(candidate)
        if path:
            return path
    return None


class LibvirtProvisioner(object):
    """Create libvirt VMs on a shared network and write Ansible inventory."""

    def __init__(
        self,
        image_path,
        hostnames,
        cache,
        artifacts,
        uri=DEFAULT_LIBVIRT_URI,
        network_name=None,
        memory_mib=DEFAULT_MEMORY_MIB,
        vcpus=DEFAULT_VCPUS,
        write_to_image=False,
        extra_ssh_args=None,
        sshd_usedns_no=False,
        disable_ipv6=False,
        debug=False,
        image_alias=None,
        use_basename=False,
        session_id=None,
        tests_dir=None,
        skip_missing_device=False,
    ):
        """Initialize a LibvirtProvisioner."""
        if libvirt is None:
            raise RuntimeError(
                "python3-libvirt is required but the libvirt module is"
                "not installed"
            )
        self.image_path = os.path.abspath(image_path)
        self.hostnames = list(hostnames)
        self.cache = cache
        self.artifacts = artifacts
        self.uri = uri
        self.network_name = network_name
        self.memory_mib = memory_mib
        self.vcpus = vcpus
        self.write_to_image = write_to_image
        self.extra_ssh_args = extra_ssh_args or ""
        self.sshd_usedns_no = sshd_usedns_no
        self.disable_ipv6 = disable_ipv6
        self.debug = debug
        self.image_alias = image_alias
        self.use_basename = use_basename
        self.session_id = session_id or uuid.uuid4().hex[:8]
        self.conn = None
        self.network = None
        self.created_network = False
        self.vms = []
        self.workdir = os.path.join(cache, "libvirt-" + self.session_id)
        self.identity_dir = None
        self.identity_file = None
        self.isomaker = find_isomaker()
        self._started = False
        self.gateway = None
        self.dns_domain = None
        self.subnet_prefix = None
        self.host_plans = {}
        self.use_static_network = False
        self.tests_dir = tests_dir
        self.skip_missing_device = skip_missing_device
        self.effective_memory_mib = memory_mib
        self.primary_nic_model = "virtio"
        self.extra_nic_models = []
        self._temp_disk_files = []
        self._qemu_device_output = None

    def _apply_fmf_config(self):
        """Load VM settings from provision.fmf if present."""
        fmf_memory = fmf_get(["qemu", "m"], None, self.tests_dir)
        if fmf_memory is not None:
            self.effective_memory_mib = int(fmf_memory)
            logging.info(
                "Using memory %s MiB from provision.fmf",
                self.effective_memory_mib,
            )
        nic_model = fmf_get(["qemu", "net_nic", "model"], None, self.tests_dir)
        if nic_model is not None:
            self.primary_nic_model = str(nic_model)
        extra_nics = fmf_get(["qemu", "net_nic_list"], [], self.tests_dir)
        if extra_nics is None:
            extra_nics = []
        self.extra_nic_models = [str(model) for model in extra_nics]

    def _qemu_supports_device(self, device):
        """Return True if qemu-kvm supports the given device name."""
        if self._qemu_device_output is None:
            for qemu_cmd in (
                "qemu-kvm",
                "/usr/libexec/qemu-kvm",
                "/usr/bin/qemu-system-x86_64",
            ):
                qemu_path = shutil.which(qemu_cmd)
                if qemu_path:
                    break
            else:
                qemu_path = None
            if qemu_path is None:
                self._qemu_device_output = ""
            else:
                self._qemu_device_output = subprocess.check_output(
                    [qemu_path, "-device", "?"],
                    stderr=subprocess.STDOUT,
                    universal_newlines=True,
                )  # nosec
        return (
            re.search(
                r'^name "%s",' % re.escape(device),
                self._qemu_device_output,
                re.M,
            )
            is not None
        )

    def _device_supported(self, device_name):
        """Return True if the host supports a qemu/libvirt device name."""
        if device_name == "nvme":
            return libvirt.getVersion() >= MIN_LIBVIRT_NVME_VERSION
        if device_name == "scsi":
            return self._qemu_supports_device("virtio-scsi-pci")
        return True

    def _mac_for_nic(self, hostname, nic_index):
        """Return a deterministic MAC for an additional network interface."""
        digest = hashlib.sha256(
            (self.session_id + "\0" + hostname + "-nic%d" % nic_index).encode()
        ).digest()
        return "52:54:00:{:02x}:{:02x}:{:02x}".format(
            digest[3], digest[4], digest[5]
        )

    def connect(self):
        """Open libvirt connection."""
        self.conn = libvirt.open(self.uri)
        if self.conn is None:
            raise RuntimeError(
                "Failed to connect to libvirt at {}".format(self.uri)
            )

    def close(self):
        """Close libvirt connection."""
        if self.conn is not None:
            self.conn.close()
            self.conn = None

    def _mac_for_host(self, hostname):
        """Return a deterministic QEMU-style MAC address for a hostname."""
        digest = hashlib.sha256(
            (self.session_id + "\0" + hostname).encode()
        ).digest()
        return "52:54:00:{:02x}:{:02x}:{:02x}".format(
            digest[0], digest[1], digest[2]
        )

    def _plan_network(self):
        """Assign gateway, DNS domain, and per-VM MAC/IP addresses."""
        subnet_octet = 120 + (int(self.session_id[:2], 16) % 100)
        self.subnet_prefix = "192.168.{}".format(subnet_octet)
        self.gateway = self.subnet_prefix + ".1"
        self.dns_domain = "lsr-{}.test".format(self.session_id)
        self.host_plans = {}
        for idx, hostname in enumerate(self.hostnames):
            self.host_plans[hostname] = {
                "mac": self._mac_for_host(hostname),
                "ip": "{}.{}".format(self.subnet_prefix, idx + 2),
            }

    def _parse_existing_network(self):
        """Read gateway and DNS domain from an existing libvirt network."""
        net_xml = self.network.XMLDesc(0)
        root = ET.fromstring(net_xml)
        ip_elem = root.find("ip")
        if ip_elem is not None and ip_elem.get("address"):
            self.gateway = ip_elem.get("address")
            address = self.gateway.rsplit(".", 1)[0]
            self.subnet_prefix = address
        domain_elem = root.find("domain")
        if domain_elem is not None and domain_elem.get("name"):
            self.dns_domain = domain_elem.get("name")
        elif not self.dns_domain:
            self.dns_domain = "lsr-{}.test".format(self.session_id)
        self.host_plans = {}
        for idx, hostname in enumerate(self.hostnames):
            self.host_plans[hostname] = {
                "mac": self._mac_for_host(hostname),
                "ip": None,
            }

    def _ensure_network(self):
        """Create or look up the virtual network shared by all VMs."""
        if self.network_name:
            self.network = self.conn.networkLookupByName(self.network_name)
            if not self.network.isActive():
                self.network.create()
            self._parse_existing_network()
            self.use_static_network = False
            logging.info(
                "Using existing libvirt network %s (gateway %s, domain %s)",
                self.network_name,
                self.gateway,
                self.dns_domain,
            )
            return
        self.use_static_network = True
        net_name = sanitize_libvirt_name("lsr-net-" + self.session_id)
        dhcp_hosts = ""
        dns_hosts = ""
        for hostname in self.hostnames:
            plan = self.host_plans[hostname]
            dhcp_hosts += (
                "      <host mac='{mac}' name='{name}' ip='{ip}'/>\n".format(
                    mac=plan["mac"], name=hostname, ip=plan["ip"]
                )
            )
            dns_hosts += (
                "    <host ip='{ip}'>\n"
                "      <hostname>{name}</hostname>\n"
                "      <hostname>{fqdn}</hostname>\n"
                "    </host>\n".format(
                    ip=plan["ip"],
                    name=hostname,
                    fqdn="{}.{}".format(hostname, self.dns_domain),
                )
            )
        net_xml = """
<network>
  <name>{name}</name>
  <forward mode='nat'/>
  <bridge name='{bridge}' stp='on' delay='0'/>
  <domain name='{dns_domain}' localOnly='yes'/>
  <dns forwardPlainNames='no'>
{dns_hosts}  </dns>
  <ip address='{gateway}' netmask='255.255.255.0'>
    <dhcp>
      <range start='{range_start}' end='{range_end}'/>
{dhcp_hosts}    </dhcp>
  </ip>
</network>
""".format(
            name=net_name,
            bridge="lsrbr" + self.session_id,
            dns_domain=self.dns_domain,
            dns_hosts=dns_hosts,
            gateway=self.gateway,
            range_start=self.subnet_prefix + ".2",
            range_end=self.subnet_prefix + ".254",
            dhcp_hosts=dhcp_hosts,
        )
        self.network = self.conn.networkDefineXML(net_xml)
        self.network.setAutostart(0)
        self.network.create()
        self.network_name = net_name
        self.created_network = True
        logging.info(
            "Created libvirt network %s on %s.0 (DNS domain %s)",
            net_name,
            self.subnet_prefix,
            self.dns_domain,
        )

    def _create_sparse_disk(self, size_bytes, directory, prefix="extra"):
        """Create a sparse disk file and return its path."""
        os.makedirs(directory, exist_ok=True)
        disk_file = tempfile.NamedTemporaryFile(
            dir=directory,
            prefix=prefix + "-",
            suffix=".img",
            delete=False,
        )
        disk_file.truncate(size_bytes)
        disk_file.close()
        self._temp_disk_files.append(disk_file.name)
        logging.info("Created temporary sparse file %s", disk_file.name)
        return disk_file.name

    def _build_extra_devices_xml(self, hostname, vm_dir):
        """Build libvirt XML for extra disks and NICs from provision.fmf."""
        controllers = []
        devices = []
        cache = "none" if self.write_to_image else "unsafe"
        virtio_letter = ord("b")
        scsi_unit = 0
        nvme_unit = 0
        scsi_controller_added = False
        usb_controller_added = False
        usb_unit = 0

        for drive in fmf_get(["qemu", "drive"], [], self.tests_dir):
            size = int(drive.get("size", 2 * 1024**3))
            path = drive.get("path")
            path = os.path.abspath(str(path)) if path is not None else vm_dir
            interface = drive.get("interface")
            if interface is None:
                interface = "virtio"
            else:
                interface = str(interface).lower()
            disk_path = self._create_sparse_disk(size, path, prefix=interface)

            if interface == "virtio":
                target = "vd{}".format(chr(virtio_letter))
                virtio_letter += 1
                devices.append("""
    <disk type='file' device='disk'>
      <driver name='qemu' type='raw' cache='{cache}'/>
      <source file='{disk}'/>
      <target dev='{target}' bus='virtio'/>
    </disk>""".format(cache=cache, disk=disk_path, target=target))  # fmt: skip
            elif interface == "nvme":
                if not self._device_supported("nvme"):
                    msg = "no NVMe support on this platform"
                    if self.skip_missing_device:
                        logging.warning("%s - skipping", msg)
                        continue
                    raise RuntimeError(msg)
                devices.append("""
    <disk type='file' device='disk'>
      <driver name='qemu' type='raw' cache='{cache}'/>
      <source file='{disk}'/>
      <target dev='nvme{unit}n1' bus='nvme'/>
      <serial>nvme-{unit}</serial>
    </disk>""".format(
                    cache=cache,
                    disk=disk_path,
                    unit=nvme_unit,
                ))  # fmt: skip
                nvme_unit += 1
            elif interface == "scsi":
                if not self._device_supported("scsi"):
                    msg = "no SCSI support on this platform"
                    if self.skip_missing_device:
                        logging.warning("%s - skipping", msg)
                        continue
                    raise RuntimeError(msg)
                if not scsi_controller_added:
                    controllers.append(
                        "    <controller type='scsi' index='0' "
                        "model='virtio-scsi'/>"
                    )
                    scsi_controller_added = True
                devices.append(
                    """
    <disk type='file' device='disk'>
      <driver name='qemu' type='raw' cache='{cache}'/>
      <source file='{disk}'/>
      <target dev='sd{target}' bus='scsi'/>
      <address type='drive' controller='0' bus='0' target='0' unit='{unit}'/>
    </disk>""".format(
                        cache=cache,
                        disk=disk_path,
                        target=chr(ord("a") + scsi_unit),
                        unit=scsi_unit,
                    )
                )  # fmt: skip
                scsi_unit += 1
            else:
                raise RuntimeError(
                    "Unsupported drive interface {!r} in provision.fmf".format(
                        interface
                    )
                )

        for usb_drive in fmf_get(["qemu", "usb_drive"], [], self.tests_dir):
            size = int(usb_drive.get("size", 1 * 1024**3))
            path = usb_drive.get("path")
            path = os.path.abspath(str(path)) if path is not None else vm_dir
            disk_path = self._create_sparse_disk(size, path, prefix="usb")
            if not usb_controller_added:
                controllers.append(
                    "    <controller type='usb' index='0' model='qemu-xhci' "
                    "ports='15'/>"
                )
                usb_controller_added = True
            devices.append(
                """
    <disk type='file' device='disk'>
      <driver name='qemu' type='raw' cache='{cache}'/>
      <source file='{disk}'/>
      <target dev='sd{target}' bus='usb' removable='on'/>
      <address type='drive' controller='0' bus='0' target='0' unit='{unit}'/>
    </disk>""".format(
                    cache=cache,
                    disk=disk_path,
                    target=chr(ord("a") + usb_unit),
                    unit=usb_unit,
                )
            )
            usb_unit += 1

        for nic_index, model in enumerate(self.extra_nic_models):
            if not self.network_name:
                raise RuntimeError(
                    "provision.fmf requests extra NICs but no primary network "
                    "is configured"
                )
            mac = self._mac_for_nic(hostname, nic_index)
            devices.append(
                """
    <interface type='network'>
      <mac address='{mac}'/>
      <source network='{network}'/>
      <model type='{model}'/>
    </interface>""".format(
                    mac=mac,
                    network=self.network_name,
                    model=model,
                )
            )

        return "".join(controllers), "".join(devices)

    def _host_inventory_name(self, hostname):
        """Return the inventory alias for a VM."""
        if self.image_alias:
            if self.image_alias == "BASENAME":
                return os.path.basename(self.image_path)
            return self.image_alias
        if self.use_basename:
            return os.path.basename(self.image_path)
        return hostname

    def _make_cloud_init(self, hostname, cloud_dir):
        """Create cloud-init ISO for the given hostname."""
        os.makedirs(cloud_dir, exist_ok=True)
        fqdn = "{}.{}".format(hostname, self.dns_domain)
        metadata = os.path.join(cloud_dir, "meta-data")
        with open(metadata, "w") as mdf:
            mdf.write(
                "instance-id: {inst}\nlocal-hostname: {host}\n".format(
                    inst="{}-{}".format(hostname, self.session_id),
                    host=hostname,
                )
            )
        userdata = os.path.join(cloud_dir, "user-data")
        with open(userdata, "w") as udf:
            udf.write(
                """#cloud-config
debug:
  verbose: true
  output: /var/log/cloud-init-debug.log
hostname: {hostname}
fqdn: {fqdn}
preserve_hostname: true
manage_etc_hosts: true
manage_resolv_conf: true
resolv_conf:
  nameservers: ['{gateway}']
  searchdomains:
    - {dns_domain}
users:
  - default
  - name: {user}
    ssh_authorized_keys:
      - ssh-rsa {key} standard-test-qcow2
ssh_pwauth: True
chpasswd:
  list: |
    {user}:{passwd}
  expire: False
""".format(
                    hostname=hostname,
                    fqdn=fqdn,
                    gateway=self.gateway,
                    dns_domain=self.dns_domain,
                    user=DEF_USER,
                    key=AUTH_KEY,
                    passwd=DEF_PASSWD,
                )
            )
            if self.sshd_usedns_no or self.disable_ipv6:
                udf.write("bootcmd:\n")
            if self.sshd_usedns_no:
                udf.write(""" - |
    if grep -q '^UseDNS' /etc/ssh/sshd_config; then
      sed 's/^UseDNS.*$/UseDNS no/' -i /etc/ssh/sshd_config
    elif grep -q '^#UseDNS' /etc/ssh/sshd_config; then
      sed 's/^#UseDNS.*$/UseDNS no/' -i /etc/ssh/sshd_config
    else
      echo "UseDNS no" >> /etc/ssh/sshd_config
    fi
""")  # fmt: skip
            if self.disable_ipv6:
                udf.write(""" - |
    {
    echo "net.ipv6.conf.all.disable_ipv6 = 1"
    echo "net.ipv6.conf.default.disable_ipv6 = 1"
    } > /etc/sysctl.d/70-disable-ipv6.conf
    sysctl -p /etc/sysctl.d/70-disable-ipv6.conf
""")  # fmt: skip
        cloudinit_iso = os.path.join(cloud_dir, "cloud-init.iso")
        null = open(os.devnull, "w")
        subprocess.check_call(  # nosec
            [
                self.isomaker,
                "-input-charset",
                "utf-8",
                "-volid",
                "cidata",
                "-joliet",
                "-rock",
                "-quiet",
                "-output",
                cloudinit_iso,
                userdata,
                metadata,
            ],
            stdout=null,
            stderr=null,
        )
        null.close()
        return cloudinit_iso

    def _disk_path_for_vm(self, hostname):
        """Return overlay disk path for a VM."""
        if self.write_to_image:
            return self.image_path
        disk_name = sanitize_libvirt_name(hostname) + ".qcow2"
        disk_path = os.path.join(self.workdir, disk_name)
        if not os.path.exists(disk_path):
            subprocess.check_call(  # nosec
                [
                    "qemu-img",
                    "create",
                    "-f",
                    "qcow2",
                    "-b",
                    self.image_path,
                    "-F",
                    "qcow2",
                    disk_path,
                ]
            )
        return disk_path

    def _domain_xml(
        self,
        domain_name,
        disk_path,
        cloudinit_iso,
        mac_address,
        extra_devices_xml="",
    ):
        """Build libvirt domain XML."""
        return """
<domain type='kvm' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'>
  <name>{name}</name>
  <memory unit='MiB'>{memory}</memory>
  <vcpu placement='static'>{vcpus}</vcpu>
  <os>
    <type arch='x86_64' machine='pc'>hvm</type>
    <boot dev='hd'/>
    <boot dev='cdrom'/>
  </os>
  <features>
    <acpi/>
    <apic/>
  </features>
  <cpu mode='host-passthrough'/>
  <clock offset='utc'/>
  <on_reboot>restart</on_reboot>
  <devices>{extra_devices}
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2' cache='{cache}'/>
      <source file='{disk}'/>
      <target dev='vda' bus='virtio'/>
    </disk>
    <disk type='file' device='cdrom'>
      <driver name='qemu' type='raw'/>
      <source file='{cloudinit}'/>
      <target dev='hda' bus='ide'/>
      <readonly/>
    </disk>
    <interface type='network'>
      <mac address='{mac}'/>
      <source network='{network}'/>
      <model type='{nic_model}'/>
    </interface>
    <console type='pty'/>
    <rng model='virtio'>
      <backend model='random'>/dev/urandom</backend>
    </rng>
  </devices>
</domain>
""".format(
            name=domain_name,
            memory=self.effective_memory_mib,
            vcpus=self.vcpus,
            cache="none" if self.write_to_image else "unsafe",
            disk=disk_path,
            cloudinit=cloudinit_iso,
            mac=mac_address,
            network=self.network_name,
            nic_model=self.primary_nic_model,
            extra_devices=extra_devices_xml,
        )

    def _get_domain_ip(self, dom):
        """Return the IPv4 address assigned to the domain, or None."""
        try:
            addrs = dom.interfaceAddresses(
                libvirt.VIR_DOMAIN_INTERFACE_ADDRESSES_SRC_LEASE, 0
            )
        except libvirt.libvirtError:
            return None
        for iface in addrs.values():
            for addr in iface.get("addrs", []):
                if addr["type"] == libvirt.VIR_IP_ADDR_TYPE_IPV4:
                    ipaddr = addr["addr"]
                    if not ipaddr.startswith("127."):
                        return ipaddr
        return None

    def _ssh_base_args(self):
        """Return common SSH command-line arguments."""
        ssh_args = [
            "ssh",
            "-o",
            "BatchMode=yes",
            "-o",
            "ConnectTimeout=5",
            "-o",
            "StrictHostKeyChecking=no",
            "-o",
            "UserKnownHostsFile=/dev/null",
            "-i",
            self.identity_file,
        ]
        if self.extra_ssh_args:
            ssh_args.extend(shlex.split(self.extra_ssh_args))
        return ssh_args

    def _ssh_run(self, ipaddr, remote_command, check=True):
        """Run a command on a VM over SSH."""
        ssh_args = self._ssh_base_args()
        ssh_args.append("{}@{}".format(DEF_USER, ipaddr))
        ssh_args.append(remote_command)
        with open(os.devnull, "w") as null:
            if check:
                subprocess.check_call(
                    ssh_args, stdout=null, stderr=null
                )  # nosec
            else:
                return subprocess.call(
                    ssh_args, stdout=null, stderr=null
                )  # nosec
        return 0

    def _wait_for_ssh(self, ipaddr):
        """Wait until SSH is available on the VM."""
        deadline = time.time() + SSH_WAIT_TIMEOUT
        while time.time() < deadline:
            if self._ssh_run(ipaddr, "/bin/true", check=False) == 0:
                return
            time.sleep(1)
        raise RuntimeError("Timed out waiting for SSH on {}".format(ipaddr))

    def _configure_peer_hostnames(self):
        """Publish all VM hostnames in /etc/hosts on every VM."""
        if len(self.vms) < 2:
            return
        entries = "\n".join(
            "{} {}".format(vm["ipaddr"], vm["hostname"]) for vm in self.vms
        )
        remote_script = """set -euo pipefail
BEGIN='{begin}'
END='{end}'
TMP=$(mktemp)
if [ -f /etc/hosts ]; then
  awk -v b="$BEGIN" -v e="$END" '
    $0 == b {{skip=1; next}}
    $0 == e {{skip=0; next}}
    skip==0 {{print}}
  ' /etc/hosts > "$TMP"
else
  : > "$TMP"
fi
printf '%s\\n' "$BEGIN" >> "$TMP"
cat >> "$TMP" <<'HOSTS'
{entries}
HOSTS
printf '%s\\n' "$END" >> "$TMP"
cat "$TMP" > /etc/hosts
rm -f "$TMP"
""".format(
            begin=HOSTS_MARKER_BEGIN,
            end=HOSTS_MARKER_END,
            entries=entries,
        )
        for vm in self.vms:
            self._ssh_run(vm["ipaddr"], remote_script)
            logging.info(
                "Configured peer hostnames on %s (%s)",
                vm["hostname"],
                vm["ipaddr"],
            )

    def start(self):
        """Create network, domains, and wait for SSH on all VMs."""
        if self._started:
            return
        if not self.isomaker:
            raise RuntimeError(
                "No ISO creation tool found (genisoimage, mkisofs, or xorriso)"
            )
        os.makedirs(self.workdir, exist_ok=True)
        os.makedirs(self.artifacts, exist_ok=True)
        self.identity_dir = os.path.join(self.workdir, "identity")
        os.makedirs(self.identity_dir, exist_ok=True)
        self.identity_file = os.path.join(self.identity_dir, "identity")
        with open(self.identity_file, "w") as idf:
            idf.write(IDENTITY)
        os.chmod(self.identity_file, 0o600)

        self.connect()
        try:
            self._apply_fmf_config()
            self._plan_network()
            self._ensure_network()
            for hostname in self.hostnames:
                plan = self.host_plans[hostname]
                domain_name = sanitize_libvirt_name(
                    "lsr-{}-{}".format(hostname, self.session_id)
                )
                vm_dir = os.path.join(self.workdir, hostname)
                cloudinit_iso = self._make_cloud_init(hostname, vm_dir)
                disk_path = self._disk_path_for_vm(hostname)
                extra_controllers, extra_devices = (
                    self._build_extra_devices_xml(hostname, vm_dir)
                )
                xml = self._domain_xml(
                    domain_name,
                    disk_path,
                    cloudinit_iso,
                    plan["mac"],
                    extra_controllers + extra_devices,
                )
                logging.debug("Domain XML:\n%s", xml)
                dom = self.conn.createXML(xml, 0)
                if dom is None:
                    raise RuntimeError(
                        "Failed to create libvirt domain {}".format(
                            domain_name
                        )
                    )
                logging.info(
                    "Started libvirt domain %s for hostname %s (mac %s)",
                    domain_name,
                    hostname,
                    plan["mac"],
                )
                ipaddr = None
                expected_ip = plan.get("ip")
                deadline = time.time() + SSH_WAIT_TIMEOUT
                while time.time() < deadline:
                    state, _ = dom.state()
                    if state == libvirt.VIR_DOMAIN_SHUTDOWN:
                        raise RuntimeError(
                            "Domain {} shut down during boot".format(
                                domain_name
                            )
                        )
                    if state == libvirt.VIR_DOMAIN_SHUTOFF:
                        raise RuntimeError(
                            "Domain {} shut off during boot".format(
                                domain_name
                            )
                        )
                    if state == libvirt.VIR_DOMAIN_CRASHED:
                        raise RuntimeError(
                            "Domain {} crashed during boot".format(domain_name)
                        )
                    ipaddr = self._get_domain_ip(dom)
                    if ipaddr:
                        if expected_ip and ipaddr != expected_ip:
                            logging.warning(
                                "VM %s got IP %s, expected %s",
                                hostname,
                                ipaddr,
                                expected_ip,
                            )
                        break
                    time.sleep(1)
                else:
                    raise RuntimeError(
                        "Timed out waiting for IP address on domain {}".format(
                            domain_name
                        )
                    )
                self._wait_for_ssh(ipaddr)
                inv_name = self._host_inventory_name(hostname)
                ssh_common = (
                    "-o UserKnownHostsFile=/dev/null "
                    "-o StrictHostKeyChecking=no"
                )
                if self.extra_ssh_args:
                    ssh_common += " " + self.extra_ssh_args
                self.vms.append(
                    {
                        "hostname": hostname,
                        "inventory_name": inv_name,
                        "domain_name": domain_name,
                        "dom": dom,
                        "ipaddr": ipaddr,
                        "host_vars": {
                            "ansible_host": ipaddr,
                            "ansible_user": DEF_USER,
                            "ansible_ssh_pass": DEF_PASSWD,
                            "ansible_ssh_private_key_file": self.identity_file,
                            "ansible_ssh_common_args": ssh_common,
                        },
                    }
                )
                logging.info(
                    "VM %s (%s) is reachable at %s",
                    hostname,
                    domain_name,
                    ipaddr,
                )
            self._configure_peer_hostnames()
            write_cleanup_script(self)
        except Exception:
            self.destroy()
            raise
        self._started = True

    def write_inventory(self, inventory_path):
        """Write YAML Ansible inventory for all running VMs."""
        hosts = {}
        for vm in self.vms:
            hosts[vm["inventory_name"]] = vm["host_vars"]
        inventory = {
            "all": {
                "children": {
                    "localhost": {"hosts": dict(hosts)},
                    "subjects": {"hosts": dict(hosts)},
                }
            }
        }
        with open(inventory_path, "w") as invf:
            yaml.safe_dump(inventory, invf, default_flow_style=False)
        logging.info("Wrote Ansible inventory to %s", inventory_path)
        return inventory_path

    def destroy(self):
        """Destroy domains, network, and temporary files."""
        if self.conn is not None:
            for vm in self.vms:
                dom = vm.get("dom")
                if dom is None:
                    continue
                domain_name = vm["domain_name"]
                try:
                    transient = not dom.isPersistent()
                    active = dom.isActive()
                    if active:
                        dom.destroy()
                    # if the domain is transient, then destroy will also
                    # undefine if we try to undefine it after destroy, we will
                    # get "Domain not found"
                    if not active or not transient:
                        dom.undefine()
                    logging.info("Destroyed libvirt domain %s", domain_name)
                except libvirt.libvirtError as err:
                    logging.warning(
                        "Error destroying domain %s: %s", domain_name, err
                    )
            if self.created_network and self.network is not None:
                try:
                    if self.network.isActive():
                        self.network.destroy()
                    self.network.undefine()
                    logging.info(
                        "Destroyed libvirt network %s", self.network_name
                    )
                except libvirt.libvirtError as err:
                    logging.warning(
                        "Error destroying network %s: %s",
                        self.network_name,
                        err,
                    )
            self.close()
        self._cleanup_temp_disks()
        self.vms = []
        self._started = False
        if not self.debug and os.path.isdir(self.workdir):
            shutil.rmtree(self.workdir, ignore_errors=True)

    def _cleanup_temp_disks(self):
        """Remove temp sparse disk files for provision.fmf drives."""
        for path in self._temp_disk_files:
            try:
                if os.path.isfile(path):
                    os.remove(path)
                    logging.info("Removed temporary disk file %s", path)
            except OSError as err:
                logging.warning("Error removing %s: %s", path, err)
        self._temp_disk_files = []

    def default_inventory_path(self):
        """Return the default Ansible inventory path inside the workdir."""
        return os.path.join(self.workdir, "inventory.yml")

    def default_cleanup_script_path(self):
        """Return the default cleanup script path inside the workdir."""
        return os.path.join(self.workdir, "cleanup.sh")


def _virsh_prefix(provisioner):
    """Return the virsh command prefix including connection URI."""
    if provisioner.uri:
        return "virsh -c {}".format(shlex.quote(provisioner.uri))
    return "virsh"


def write_cleanup_script(provisioner):
    """Write a shell script that cleans up VMs and removes the workdir."""
    script_path = provisioner.default_cleanup_script_path()
    virsh_prefix = _virsh_prefix(provisioner)
    lines = [
        "#!/bin/bash",
        "# Clean up libvirt VMs created by runlibvirt.py",
        "set -uxo pipefail",
        "exec 2>&1",
        f"WORKDIR={shlex.quote(provisioner.workdir)}",
    ]
    # not sure why undefine says 'failed to get domain', but it's not a problem
    for vm in provisioner.vms:
        domain_name = vm["domain_name"]
        lines.extend(
            [
                "{prefix} destroy {domain}".format(
                    prefix=virsh_prefix,
                    domain=shlex.quote(domain_name),
                ),
                (
                    "{prefix} undefine {domain} 2>&1 | "
                    "grep -v 'failed to get domain'"
                ).format(
                    prefix=virsh_prefix,
                    domain=shlex.quote(domain_name),
                ),
            ]
        )
    if provisioner.created_network and provisioner.network_name:
        network_name = provisioner.network_name
        lines.extend(
            [
                "{prefix} net-destroy {network}".format(
                    prefix=virsh_prefix,
                    network=shlex.quote(network_name),
                ),
                "{prefix} net-undefine {network}".format(
                    prefix=virsh_prefix,
                    network=shlex.quote(network_name),
                ),
            ]
        )
    lines.extend(
        [
            "cd /",
            'rm -rf "$WORKDIR"',
            "{prefix} list --all".format(prefix=virsh_prefix),
            "{prefix} net-list --all".format(prefix=virsh_prefix),
            'echo "Cleanup complete."',
        ]
    )
    with open(script_path, "w") as script_file:
        script_file.write("\n".join(lines))
    os.chmod(script_path, 0o755)  # nosec
    logging.info("Wrote cleanup script to %s", script_path)
    return script_path


def print_debug_cleanup_instructions(provisioner, inventory_path=None):
    """Print instructions for connecting to and cleaning up debug VMs."""
    if provisioner is None or not provisioner.debug:
        return
    if inventory_path is None:
        inventory_path = provisioner.default_inventory_path()
    cleanup_script = provisioner.default_cleanup_script_path()
    lines = [
        "",
        "Debug mode: libvirt VMs were left running.",
        "Workdir: {}".format(provisioner.workdir),
        "Ansible inventory: {}".format(inventory_path),
        "Cleanup script: {}".format(cleanup_script),
        "SSH private key: {}".format(provisioner.identity_file),
        "SSH password: {}".format(DEF_PASSWD),
        "",
        "Connect to a VM:",
    ]
    for vm in provisioner.vms:
        lines.append(
            "  ssh -i {key} -o StrictHostKeyChecking=no -o "
            "UserKnownHostsFile=/dev/null {user}@{ip}  # {host}".format(
                key=provisioner.identity_file,
                user=DEF_USER,
                ip=vm["ipaddr"],
                host=vm["hostname"],
            )
        )
    lines.extend(
        [
            "",
            "Run ansible-playbook again:",
            "  ansible-playbook -i {} ...".format(inventory_path),
            "",
            "Cleanup VMs and remove the workdir:",
            "  {}".format(cleanup_script),
            "",
        ]
    )
    for line in lines:
        print(line, file=sys.stderr)


def resolve_hostnames(args):
    """Build hostname list from command-line arguments."""
    if args.hostnames:
        names = []
        for item in args.hostnames:
            names.extend([name for name in item.split(",") if name])
        if names:
            return validate_hostnames(names)
    if args.num_vms < 1:
        raise ValueError("--num-vms must be at least 1")
    prefix = args.hostname_prefix or "vm"
    width = max(2, len(str(args.num_vms)))
    names = [
        "{}{:0{width}d}".format(prefix, idx, width=width)
        for idx in range(1, args.num_vms + 1)
    ]
    return validate_hostnames(names)


def stop_libvirt(provisioner, lock_on_file=None):
    """Cleanup libvirt VMs unless debug mode or lock file still present."""
    if provisioner is None:
        return
    if lock_on_file and os.path.exists(lock_on_file):
        return
    if provisioner.debug:
        logging.info(
            "Debug mode - leaving libvirt VMs running. "
            "See cleanup instructions printed at end of run."
        )
        return
    provisioner.destroy()


def internal_run_ansible_playbooks_libvirt(
    provisioner,
    inventory_path,
    test_env,
    ansible_args,
    playbooks,
    cwd,
    ansible_container,
    wait_on_vm=False,
    log_file=None,
    last_rc=0,
    batch_rc=0,
    start_vms=True,
):
    """Run ansible-playbook using libvirt-provisioned inventory."""
    lock_on_file = test_env.get("LOCK_ON_FILE")
    if start_vms:
        provisioner.start()
        provisioner.write_inventory(inventory_path)
    try:
        with rq.file_or_stdout(log_file) as (stdout, stderr):
            if ansible_container:
                rq.run_ansible_container(
                    test_env,
                    inventory_path,
                    ansible_args,
                    playbooks,
                    cwd,
                    ansible_container,
                    stdout,
                    stderr,
                    last_rc,
                    batch_rc,
                )
            else:
                subprocess.check_call(  # nosec
                    [
                        "ansible-playbook",
                        "-vv",
                        "--inventory=" + inventory_path,
                        "-e",
                        "last_rc=" + str(last_rc),
                        "-e",
                        "batch_rc=" + str(batch_rc),
                    ]
                    + ansible_args
                    + playbooks,
                    env=test_env,
                    cwd=cwd,
                    stdout=stdout,
                    stderr=stderr,
                )
    finally:
        if wait_on_vm:
            stop_libvirt(provisioner, lock_on_file)


def refresh_snapshot_libvirt(
    image_file,
    snapfile,
    provisioner_kwargs,
    test_env,
    ansible_args,
    setup_yml,
    cwd,
    post_snap_sleep_time,
    log_file,
    ansible_container,
):
    """Create snapshot using a libvirt VM with write_to_image."""
    need_refresh = False
    if not os.path.isfile(snapfile):
        need_refresh = True
        logging.info("Creating snapshot because %s does not exist", snapfile)
    else:
        snap_stats = os.stat(snapfile)
        file_stats = os.stat(image_file)
        now = time.time()
        if now - snap_stats.st_ctime > 86400:
            need_refresh = True
            logging.info("Creating snapshot because %s is too old", snapfile)
        elif snap_stats.st_ctime < file_stats.st_ctime:
            need_refresh = True
            logging.info(
                "Creating snapshot because %s is older than backing file %s",
                snapfile,
                image_file,
            )
    if not need_refresh:
        return
    with rq.file_or_stdout(log_file) as (stdout, stderr):
        subprocess.check_call(  # nosec
            [
                "qemu-img",
                "create",
                "-f",
                "qcow2",
                "-b",
                image_file,
                "-F",
                "qcow2",
                snapfile,
            ],
            stdout=stdout,
            stderr=stderr,
        )
    snap_kwargs = dict(provisioner_kwargs)
    snap_kwargs["image_path"] = snapfile
    snap_kwargs["hostnames"] = [snap_kwargs["hostnames"][0]]
    snap_kwargs["write_to_image"] = True
    snap_kwargs["debug"] = False
    provisioner = LibvirtProvisioner(**snap_kwargs)
    inventory_path = tempfile.NamedTemporaryFile(
        suffix=".yml", delete=False
    ).name
    test_env_setup = {}
    test_env_setup.update(test_env)
    if "TEST_DEBUG" in test_env_setup:
        del test_env_setup["TEST_DEBUG"]
    if "TEST_ARTIFACTS" in test_env_setup:
        test_env_setup["TEST_ARTIFACTS"] = (
            test_env_setup["TEST_ARTIFACTS"] + ".snap"
        )
    if "LOCK_ON_FILE" in test_env_setup:
        del test_env_setup["LOCK_ON_FILE"]
    try:
        internal_run_ansible_playbooks_libvirt(
            provisioner,
            inventory_path,
            test_env_setup,
            ansible_args,
            setup_yml,
            cwd,
            ansible_container,
            wait_on_vm=True,
            log_file=log_file,
            start_vms=True,
        )
    finally:
        provisioner.destroy()
        if os.path.exists(inventory_path):
            os.unlink(inventory_path)
    logging.info(
        "Created snapshot %s - sleeping %d seconds to allow disk sync",
        snapfile,
        post_snap_sleep_time,
    )
    time.sleep(post_snap_sleep_time)
    subprocess.check_call(["/bin/sync"])  # nosec


def run_ansible_playbooks_libvirt(  # noqa: C901
    image,
    hostnames,
    setup_yml,
    cleanup_yml,
    test_env,
    debug,
    image_alias,
    collection_path,
    artifacts,
    ansible_args,
    use_snapshot,
    use_ansible_log,
    wait_on_vm,
    write_inventory,
    erase_old_snapshot,
    post_snap_sleep_time,
    batch_file,
    batch_report,
    log_file,
    tests_dir,
    make_batch,
    ansible_container,
    make_batch_file_order,
    libvirt_uri,
    libvirt_network,
    memory_mib,
    vcpus,
    remove_cloud_init,
    use_yum_cache,
    cache,
    sshd_usedns_no,
    disable_ipv6,
    skip_missing_device=False,
):
    """Run playbooks against libvirt-managed VMs."""
    test_env.update(dict(os.environ))
    ansible_args, playbooks = rq.split_args_and_playbooks(ansible_args)
    if make_batch:
        batch_file = "batch.txt"
        batch_report = "batch.report"
        rq.make_batch_file(
            batch_file, tests_dir, ansible_args, image, make_batch_file_order
        )
    batches = rq.get_batches_from_playbooks_and_args(
        ansible_args,
        playbooks,
        setup_yml,
        cleanup_yml,
        batch_file,
    )
    batch_inventory = None
    rc = 0
    batch_rc = 0
    lock_on_file = None
    if batch_file or cleanup_yml or ansible_container:
        if not write_inventory:
            batch_inventory = tempfile.NamedTemporaryFile(suffix=".yml").name
            write_inventory = batch_inventory
        lock_on_file = tempfile.NamedTemporaryFile().name
        test_env["LOCK_ON_FILE"] = lock_on_file

    image_file = image["file"]
    snapfile = image_file + ".snap"
    if image_alias:
        if len(hostnames) > 1 and image_alias not in (None, "BASENAME"):
            logging.warning(
                "image-alias applies to all VMs; use per-VM hostnames instead"
            )
    if collection_path:
        test_env[rq.COLL_PATH_ENV_VAR] = collection_path

    inventory_path = write_inventory
    if not inventory_path:
        inventory_path = tempfile.NamedTemporaryFile(suffix=".yml").name

    extra_ssh_args = os.environ.get("TEST_EXTRA_SSH_ARGS", "")
    provisioner_kwargs = {
        "image_path": image_file,
        "hostnames": hostnames,
        "cache": cache,
        "artifacts": artifacts or os.path.abspath("artifacts"),
        "uri": libvirt_uri,
        "network_name": libvirt_network,
        "memory_mib": memory_mib,
        "vcpus": vcpus,
        "extra_ssh_args": extra_ssh_args,
        "sshd_usedns_no": sshd_usedns_no,
        "disable_ipv6": disable_ipv6,
        "debug": debug,
        "image_alias": image_alias,
        "tests_dir": tests_dir,
        "skip_missing_device": skip_missing_device,
    }
    provisioner = None
    debug_provisioner = None
    debug_inventory_path = None
    vms_started = False

    try:
        for batch in batches:
            if not batch.playbooks:
                continue
            if batch.args and batch.args.debug:
                test_env["TEST_DEBUG"] = "true"
            elif debug and not batch_file:
                test_env["TEST_DEBUG"] = "true"
            elif "TEST_DEBUG" in test_env:
                del test_env["TEST_DEBUG"]
            if batch.args and batch.args.artifacts:
                test_env["TEST_ARTIFACTS"] = batch.args.artifacts
            elif artifacts:
                test_env["TEST_ARTIFACTS"] = artifacts
            elif "TEST_ARTIFACTS" not in test_env:
                test_env["TEST_ARTIFACTS"] = "artifacts"
            test_env["TEST_ARTIFACTS"] = os.path.abspath(
                test_env["TEST_ARTIFACTS"]
            )
            if use_ansible_log and "ANSIBLE_LOG_PATH" not in os.environ:
                test_env["ANSIBLE_LOG_PATH"] = os.path.join(
                    test_env["TEST_ARTIFACTS"], "ansible.log"
                )
            os.makedirs(test_env["TEST_ARTIFACTS"], exist_ok=True)

            if batch.args and batch.args.log_file:
                local_log_file = os.path.abspath(batch.args.log_file)
            elif log_file:
                local_log_file = os.path.abspath(log_file)
            else:
                local_log_file = None

            if batch.args and batch.args.tests_dir:
                cwd = batch.args.tests_dir
            elif tests_dir:
                cwd = tests_dir
            else:
                cwd = os.path.dirname(batch.playbooks[0])
            provisioner_kwargs["tests_dir"] = cwd

            if (
                (batch.args and batch.args.erase_old_snapshot)
                or erase_old_snapshot
            ) and os.path.exists(snapfile):
                os.unlink(snapfile)

            current_image = image_file
            if (batch.args and batch.args.use_snapshot) or use_snapshot:
                current_image = snapfile
                refresh_snapshot_libvirt(
                    image_file,
                    snapfile,
                    provisioner_kwargs,
                    test_env,
                    batch.ansible_args,
                    batch.setup_playbooks,
                    cwd,
                    post_snap_sleep_time,
                    local_log_file,
                    ansible_container,
                )
                playbooks_to_run = batch.playbooks
            else:
                playbooks_to_run = batch.setup_playbooks + batch.playbooks

            if (
                provisioner is None
                or provisioner.image_path != os.path.abspath(current_image)
            ):
                if provisioner is not None:
                    stop_libvirt(provisioner, lock_on_file)
                    vms_started = False
                pk = dict(provisioner_kwargs)
                pk["image_path"] = current_image
                pk["artifacts"] = test_env["TEST_ARTIFACTS"]
                pk["debug"] = bool(test_env.get("TEST_DEBUG"))
                provisioner = LibvirtProvisioner(**pk)
                if provisioner.debug:
                    debug_provisioner = provisioner
                    if not write_inventory:
                        inventory_path = provisioner.default_inventory_path()
                    debug_inventory_path = inventory_path

            rq.handle_vault(
                cwd, batch.ansible_args, playbooks_to_run, test_env
            )
            if local_log_file:
                logging.info("Running playbooks %s", str(playbooks_to_run))
            last_rc = rc
            rc = 0
            start_ts = time.time()
            try:
                internal_run_ansible_playbooks_libvirt(
                    provisioner,
                    inventory_path,
                    test_env,
                    batch.ansible_args,
                    playbooks_to_run,
                    cwd,
                    ansible_container,
                    wait_on_vm,
                    local_log_file,
                    last_rc,
                    batch_rc,
                    start_vms=not vms_started,
                )
                if wait_on_vm:
                    vms_started = False
                    provisioner = None
                else:
                    vms_started = True
                if local_log_file:
                    logging.info("Playbook run was successful")
            except subprocess.CalledProcessError as cpe:
                rc = cpe.returncode
                if batch_rc == 0:
                    batch_rc = rc
                if local_log_file:
                    logging.error("Playbook run failed with error %d", rc)
            if batch_report:
                if batch.args and batch.args.batch_id:
                    batch_id_str = " " + batch.args.batch_id
                else:
                    batch_id_str = ""
                with open(batch_report, "a") as br:
                    br.write(
                        "%d %f %f%s %s\n"
                        % (
                            rc,
                            start_ts,
                            time.time(),
                            batch_id_str,
                            " ".join(playbooks_to_run),
                        )
                    )
            if batch_inventory and debug_provisioner is None:
                inventory_path = batch_inventory
    finally:
        if lock_on_file and os.path.exists(lock_on_file):
            os.unlink(lock_on_file)
        stop_libvirt(provisioner, None)
        if debug_provisioner is not None:
            print_debug_cleanup_instructions(
                debug_provisioner,
                debug_inventory_path or inventory_path,
            )
        if batch_inventory and os.path.exists(batch_inventory):
            os.unlink(batch_inventory)
        elif (
            not write_inventory
            and inventory_path
            and os.path.exists(inventory_path)
            and debug_provisioner is None
        ):
            os.unlink(inventory_path)
    if batch_rc != 0:
        raise Exception("One or more tests failed")


def runlibvirt(
    image,
    cache,
    hostnames,
    remove_cloud_init=False,
    collection_path=None,
    use_yum_cache=False,
    sourcedir=".",
    pretty=True,
    profile=True,
    profile_task_limit=rq.DEFAULT_PROFILE_TASK_LIMIT,
    debug=False,
    image_alias=None,
    artifacts=None,
    ansible_args=None,
    use_snapshot=False,
    use_ansible_log=False,
    setup_yml=None,
    cleanup_yml=None,
    wait_on_vm=False,
    write_inventory=None,
    erase_old_snapshot=False,
    post_snap_sleep_time=rq.DEFAULT_POST_SNAP_SLEEP_TIME,
    batch_file=None,
    batch_report=None,
    log_file=None,
    tests_dir=None,
    collection=False,
    make_batch=None,
    ansible_container=None,
    make_batch_file_order=None,
    lsr_report_errors_url=None,
    skip_requirements=False,
    skip_callback_plugins=False,
    libvirt_uri=DEFAULT_LIBVIRT_URI,
    libvirt_network=None,
    memory_mib=DEFAULT_MEMORY_MIB,
    vcpus=DEFAULT_VCPUS,
    sshd_usedns_no=False,
    disable_ipv6=False,
    skip_missing_device=False,
):
    """Download image, provision libvirt VMs, run playbooks."""
    if write_inventory:
        basename = os.path.basename(write_inventory)
        if basename != "inventory" and os.path.splitext(basename)[1] != ".yml":
            fmtstr = (
                "Write inventory file {} must be named 'inventory' or must "
                "end in '.yml'"
            )
            errmsg = fmtstr.format(write_inventory)
            logging.critical(errmsg)
            raise Exception(errmsg)
    rq.download_image(image, cache)
    pre_setup_yml, post_setup_yml = rq.make_setup_yml(
        image, cache, remove_cloud_init, use_snapshot, use_yum_cache
    )
    local_setup_yml = []
    if pre_setup_yml:
        local_setup_yml.append(pre_setup_yml)
    if setup_yml:
        local_setup_yml.extend(setup_yml)
    if post_setup_yml:
        local_setup_yml.append(post_setup_yml)
    local_cleanup_yml = cleanup_yml or []
    if collection_path is None and "TOX_WORK_DIR" in os.environ:
        collection_path = os.environ["TOX_WORK_DIR"]
    test_env = dict(image.get("env", {}))
    test_env["ANSIBLE_INVENTORY_ANY_UNPARSED_IS_FAILED"] = "true"
    test_env["ANSIBLE_INJECT_FACT_VARS"] = "false"
    if use_yum_cache:
        logging.warning(
            "use-yum-cache is not yet supported with runlibvirt; ignoring"
        )
    if not skip_requirements:
        rq.install_requirements(
            sourcedir, collection_path, test_env, collection
        )
    if not skip_callback_plugins:
        rq.setup_callback_plugins(
            pretty, profile, profile_task_limit, test_env
        )
    rq.get_lsr_report_errors_script(lsr_report_errors_url, test_env)
    if ansible_args is None:
        ansible_args = []
    run_ansible_playbooks_libvirt(
        image,
        hostnames,
        local_setup_yml,
        local_cleanup_yml,
        test_env,
        debug,
        image_alias,
        collection_path,
        artifacts,
        ansible_args,
        use_snapshot,
        use_ansible_log,
        wait_on_vm,
        write_inventory,
        erase_old_snapshot,
        post_snap_sleep_time,
        batch_file,
        batch_report,
        log_file,
        tests_dir,
        make_batch,
        ansible_container,
        make_batch_file_order,
        libvirt_uri,
        libvirt_network,
        memory_mib,
        vcpus,
        remove_cloud_init,
        use_yum_cache,
        cache,
        sshd_usedns_no,
        disable_ipv6,
        skip_missing_device,
    )


def get_arg_parser():
    """Return argparse parser for runlibvirt arguments."""
    parser = rq.get_arg_parser()
    parser.description = "Launch libvirt integration tests."
    parser.epilog = rq.help_epilog()
    parser.add_argument(
        "--hostnames",
        action="append",
        default=[],
        help=(
            "Hostname for each VM.  May be given multiple times or as a "
            "comma-separated list.  Each VM gets its own libvirt domain and "
            "inventory entry.  All VMs share a virtual network."
        ),
    )
    parser.add_argument(
        "--num-vms",
        type=int,
        default=int(os.environ.get("LSR_LIBVIRT_NUM_VMS", "1")),
        help=(
            "Number of VMs to create when --hostnames is not used "
            "(default: 1)."
        ),
    )
    parser.add_argument(
        "--hostname-prefix",
        default=os.environ.get("LSR_LIBVIRT_HOSTNAME_PREFIX", "vm"),
        help=(
            "Prefix for auto-generated hostnames when using --num-vms "
            "(default: vm -> vm01, vm02, ...)."
        ),
    )
    parser.add_argument(
        "--libvirt-uri",
        default=os.environ.get("LSR_LIBVIRT_URI", DEFAULT_LIBVIRT_URI),
        help="Libvirt connection URI (default: qemu:///system).",
    )
    parser.add_argument(
        "--libvirt-network",
        default=os.environ.get("LSR_LIBVIRT_NETWORK"),
        help=(
            "Existing libvirt network name to attach VMs to.  "
            "If omitted, a transient NAT network is created."
        ),
    )
    parser.add_argument(
        "--memory",
        type=int,
        default=int(
            os.environ.get("LSR_LIBVIRT_MEMORY", str(DEFAULT_MEMORY_MIB))
        ),
        help="VM memory in MiB (default: {}).".format(DEFAULT_MEMORY_MIB),
    )
    parser.add_argument(
        "--vcpus",
        type=int,
        default=int(os.environ.get("LSR_LIBVIRT_VCPUS", str(DEFAULT_VCPUS))),
        help="Number of vCPUs per VM (default: {}).".format(DEFAULT_VCPUS),
    )
    parser.add_argument(
        "--sshd-usedns-no",
        action="store_true",
        default=bool(
            rq.strtobool(os.environ.get("LSR_LIBVIRT_SSHD_USEDNS_NO", "False"))
        ),
        help="Configure VMs to use 'UseDNS no' in sshd.",
    )
    parser.add_argument(
        "--disable-ipv6",
        action="store_true",
        default=bool(
            rq.strtobool(os.environ.get("LSR_LIBVIRT_DISABLE_IPV6", "False"))
        ),
        help="Disable IPv6 in VMs via cloud-init.",
    )
    parser.add_argument(
        "--wait-on-vm",
        action="store_true",
        default=bool(
            rq.strtobool(os.environ.get("LSR_LIBVIRT_WAIT_ON_VM", "False"))
        ),
        help="Destroy VMs after each ansible-playbook invocation.",
    )
    parser.add_argument(
        "--skip-missing-device",
        action="store_true",
        default=bool(
            rq.strtobool(os.environ.get("TEST_SKIP_MISSING_DEVICE", "False"))
        ),
        help=(
            "Skip unsupported extra disk devices from provision.fmf instead "
            "of failing."
        ),
    )
    # Remove qemu-specific inventory option; libvirt writes YAML inventory.
    for action in list(parser._actions):
        if action.dest == "inventory":
            parser._actions.remove(action)
            for opt in list(action.option_strings):
                parser._option_string_actions.pop(opt, None)
    return parser


def main():
    """Execute the main function."""
    parser = get_arg_parser()
    args, ansible_args = parser.parse_known_args()
    args.ansible_args = ansible_args
    if not args.setup_yml and "LSR_LIBVIRT_SETUP_YML" in os.environ:
        args.setup_yml = os.environ["LSR_LIBVIRT_SETUP_YML"].split(",")
    elif not args.setup_yml and "LSR_QEMU_SETUP_YML" in os.environ:
        args.setup_yml = os.environ["LSR_QEMU_SETUP_YML"].split(",")
    if not args.cleanup_yml and "LSR_LIBVIRT_CLEANUP_YML" in os.environ:
        args.cleanup_yml = os.environ["LSR_LIBVIRT_CLEANUP_YML"].split(",")
    elif not args.cleanup_yml and "LSR_QEMU_CLEANUP_YML" in os.environ:
        args.cleanup_yml = os.environ["LSR_QEMU_CLEANUP_YML"].split(",")
    logging.getLogger().setLevel(getattr(logging, args.log_level.upper()))
    if not any([args.image_name, args.image_file]) or all(
        [args.image_name, args.image_file]
    ):
        logging.critical(
            "One, and only one, of --image-name or --image-file must be given."
        )
        sys.exit(1)
    if args.post_snap_sleep_time == 0:
        args.post_snap_sleep_time = rq.DEFAULT_POST_SNAP_SLEEP_TIME
    os.makedirs(args.cache, exist_ok=True)
    if args.make_batch_file_order:
        args.make_batch = True
    elif args.make_batch:
        args.make_batch_file_order = "imagehash"

    rq.prep_el6(args)
    try:
        hostnames = resolve_hostnames(args)
    except ValueError as err:
        logging.critical(str(err))
        sys.exit(1)
    image = rq.get_image_config(args)
    wait_on_vm = args.wait_on_vm or args.wait_on_qemu
    runlibvirt(
        image,
        args.cache,
        hostnames,
        remove_cloud_init=args.remove_cloud_init,
        use_yum_cache=args.use_yum_cache,
        pretty=args.pretty,
        profile=args.profile,
        profile_task_limit=args.profile_task_limit,
        debug=args.debug,
        image_alias=args.image_alias,
        artifacts=args.artifacts,
        ansible_args=args.ansible_args,
        use_snapshot=args.use_snapshot,
        use_ansible_log=True,
        setup_yml=args.setup_yml,
        cleanup_yml=args.cleanup_yml,
        wait_on_vm=wait_on_vm,
        write_inventory=args.write_inventory,
        erase_old_snapshot=args.erase_old_snapshot,
        post_snap_sleep_time=args.post_snap_sleep_time,
        batch_file=args.batch_file,
        batch_report=args.batch_report,
        log_file=args.log_file,
        tests_dir=args.tests_dir,
        collection=args.collection,
        make_batch=args.make_batch,
        ansible_container=args.ansible_container,
        make_batch_file_order=args.make_batch_file_order,
        lsr_report_errors_url=args.lsr_report_errors_url,
        skip_requirements=args.skip_requirements,
        skip_callback_plugins=args.skip_callback_plugins,
        libvirt_uri=args.libvirt_uri,
        libvirt_network=args.libvirt_network,
        memory_mib=args.memory,
        vcpus=args.vcpus,
        sshd_usedns_no=args.sshd_usedns_no,
        disable_ipv6=args.disable_ipv6,
        skip_missing_device=args.skip_missing_device,
    )


if __name__ == "__main__":
    main()
