# SPDX-License-Identifier: MIT

[build-system]
requires = ["setuptools >=40.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79
exclude = ".github"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 79

[tool.pylint.format]
max-line-length = 79

[tool.pylint."message control"]
disable = "R0205,R0801"
