name: tox
on:  # yamllint disable-line rule:truthy
  - pull_request
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # note 3.11 not working as of 2022-07-05 - revisit soon
        pyver: ['2.7', '3.6', '3.8', '3.9', '3.10']
    steps:
      - name: checkout PR
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.pyver }}
      - name: Install platform dependencies, python, tox
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          pip install -rtox-requirements.txt
      - name: Run tox tests
        run: |
          set -euxo pipefail
          toxpyver=$(echo "${{ matrix.pyver }}" | tr -d .)
          case "$toxpyver" in
          *-alpha*|*-beta*) toxpyver=$(echo "$toxpyver" | sed 's/^.* \([1-9][0-9]*\)$/\1/') ;;
          27) export SAFETY_CMD="echo skipping safety" ;;
          esac
          toxpyenv="py${toxpyver}-tox30"
          # run python unit tests only on the toxenv that matches the
          # current system version of python
          tox -e "black,isort,pylint,flake8,bandit,pydocstyle,$toxpyenv,coveralls"
  python-26:
    runs-on: ubuntu-16.04
    steps:
      - name: checkout PR
        uses: actions/checkout@v2
      - name: Install python, dependencies
        run: |
          set -euo pipefail
          curl -sSf --retry 5 -o python-2.6.tar.bz2 ${PY26URL}
          sudo tar xjf python-2.6.tar.bz2 --directory /
          myuid=$(id -u)
          mygid=$(id -g)
          sudo chown -R $myuid:$mygid /home/travis/virtualenv
          source /home/travis/virtualenv/python2.6/bin/activate
          set -x
          pip install -rtox-requirements.txt
        env:
          # yamllint disable-line rule:line-length
          PY26URL: https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/14.04/x86_64/python-2.6.tar.bz2
          VIRTUAL_ENV_DISABLE_PROMPT: "true"
      - name: Run tox tests
        run: |
          set -euo pipefail
          source /home/travis/virtualenv/python2.6/bin/activate
          set -x
          tox -e py26-tox20,coveralls26
        env:
          SAFETY_CMD: "echo skipping safety"
          VIRTUAL_ENV_DISABLE_PROMPT: "true"
          COVERALLS_CMD: "echo skipping report in py26-tox20 - will use separate testenv"
